// <auto-generated />
using System.Globalization;
using System.Resources;

namespace Toolbox.Resources;

/// <summary>
/// Stellt zentral verwaltete Anzeigetexte bereit.
/// </summary>
public static class DisplayTexts
{
    private static readonly ResourceManager ResourceManager = new("Toolbox.Resources.DisplayTexts", typeof(DisplayTexts).Assembly);

    private static string GetString(string resourceKey) => ResourceManager.GetString(resourceKey, CultureInfo.CurrentUICulture) ?? string.Empty;

    public static string HomePageTitle => GetString(nameof(HomePageTitle));
    public static string HomeWelcomeTitle => GetString(nameof(HomeWelcomeTitle));
    public static string HomeWelcomeDescription => GetString(nameof(HomeWelcomeDescription));
    public static string HomeTarotOverviewButton => GetString(nameof(HomeTarotOverviewButton));
    public static string TarotPageTitle => GetString(nameof(TarotPageTitle));
    public static string TarotHeader => GetString(nameof(TarotHeader));
    public static string TarotSearchLabel => GetString(nameof(TarotSearchLabel));
    public static string TarotSearchPlaceholder => GetString(nameof(TarotSearchPlaceholder));
    public static string TarotSearchNotFound => GetString(nameof(TarotSearchNotFound));
    public static string TarotDescriptionLoading => GetString(nameof(TarotDescriptionLoading));
    public static string TarotDescriptionLoadError => GetString(nameof(TarotDescriptionLoadError));
    public static string TarotPreviousCardButton => GetString(nameof(TarotPreviousCardButton));
    public static string TarotNextCardButton => GetString(nameof(TarotNextCardButton));
    public static string TarotDeckSelectionLabel => GetString(nameof(TarotDeckSelectionLabel));
    public static string NavigationBrand => GetString(nameof(NavigationBrand));
    public static string NavigationToggleTitle => GetString(nameof(NavigationToggleTitle));
    public static string NavigationHome => GetString(nameof(NavigationHome));
    public static string NavigationTarotCards => GetString(nameof(NavigationTarotCards));
    public static string NavigationBackupRestore => GetString(nameof(NavigationBackupRestore));
    public static string NavigationImportExport => GetString(nameof(NavigationImportExport));
    public static string NavigationSettings => GetString(nameof(NavigationSettings));
    public static string BackupRestorePageTitle => GetString(nameof(BackupRestorePageTitle));
    public static string BackupRestorePageHeader => GetString(nameof(BackupRestorePageHeader));
    public static string ImportExportPageTitle => GetString(nameof(ImportExportPageTitle));
    public static string ImportExportPageHeader => GetString(nameof(ImportExportPageHeader));
    public static string ImportExportDeckImportHeading => GetString(nameof(ImportExportDeckImportHeading));
    public static string ImportExportDeckUploadLabel => GetString(nameof(ImportExportDeckUploadLabel));
    public static string ImportExportDeckUploadHint => GetString(nameof(ImportExportDeckUploadHint));
    public static string ImportExportDeckInvalidFileType => GetString(nameof(ImportExportDeckInvalidFileType));
    public static string ImportExportDeckFileTooLarge => GetString(nameof(ImportExportDeckFileTooLarge));
    public static string ImportExportDeckImportInProgress => GetString(nameof(ImportExportDeckImportInProgress));
    public static string ImportExportDeckImportSuccess => GetString(nameof(ImportExportDeckImportSuccess));
    public static string ImportExportDeckImportFailedFormat => GetString(nameof(ImportExportDeckImportFailedFormat));
    public static string ImportExportDeckMissingDeckName => GetString(nameof(ImportExportDeckMissingDeckName));
    public static string ImportExportDeckArchiveEmpty => GetString(nameof(ImportExportDeckArchiveEmpty));
    public static string ImportExportDeckNoCardsFound => GetString(nameof(ImportExportDeckNoCardsFound));
    public static string ImportExportDeckMissingImageFormat => GetString(nameof(ImportExportDeckMissingImageFormat));
    public static string ImportExportDeckMissingDescriptionFormat => GetString(nameof(ImportExportDeckMissingDescriptionFormat));
    public static string ImportExportDeckReportTitleFormat => GetString(nameof(ImportExportDeckReportTitleFormat));
    public static string ImportExportDeckReportImageLengthLabel => GetString(nameof(ImportExportDeckReportImageLengthLabel));
    public static string ImportExportDeckReportDescriptionLengthLabel => GetString(nameof(ImportExportDeckReportDescriptionLengthLabel));
    public static string ImportExportDeckReportCloseButtonLabel => GetString(nameof(ImportExportDeckReportCloseButtonLabel));
    public static string SettingsPageTitle => GetString(nameof(SettingsPageTitle));
    public static string SettingsPageHeader => GetString(nameof(SettingsPageHeader));
    public static string SettingsSplashDurationLabel => GetString(nameof(SettingsSplashDurationLabel));
    public static string SettingsSplashDurationDescription => GetString(nameof(SettingsSplashDurationDescription));
    public static string NotFoundPageTitle => GetString(nameof(NotFoundPageTitle));
    public static string NotFoundMessage => GetString(nameof(NotFoundMessage));
}
