// <auto-generated />
using System.Globalization;
using System.Resources;

namespace Toolbox.Resources;

/// <summary>
/// Stellt zentral verwaltete Anzeigetexte bereit.
/// </summary>
public static class DisplayTexts
{
    private static readonly ResourceManager ResourceManager = new("Toolbox.Resources.DisplayTexts", typeof(DisplayTexts).Assembly);

    private static string GetString(string resourceKey) => ResourceManager.GetString(resourceKey, CultureInfo.CurrentUICulture) ?? string.Empty;

    public static string HomePageTitle => GetString(nameof(HomePageTitle));
    public static string HomeWelcomeTitle => GetString(nameof(HomeWelcomeTitle));
    public static string HomeWelcomeDescription => GetString(nameof(HomeWelcomeDescription));
    public static string HomeTarotOverviewButton => GetString(nameof(HomeTarotOverviewButton));
    public static string TarotPageTitle => GetString(nameof(TarotPageTitle));
    public static string TarotSearchLabel => GetString(nameof(TarotSearchLabel));
    public static string TarotSearchPlaceholder => GetString(nameof(TarotSearchPlaceholder));
    public static string TarotSearchNotFound => GetString(nameof(TarotSearchNotFound));
    public static string TarotDescriptionLoading => GetString(nameof(TarotDescriptionLoading));
    public static string TarotDescriptionLoadError => GetString(nameof(TarotDescriptionLoadError));
    public static string TarotPreviousCardButton => GetString(nameof(TarotPreviousCardButton));
    public static string TarotNextCardButton => GetString(nameof(TarotNextCardButton));
    public static string TarotScrollToDescriptionLabel => GetString(nameof(TarotScrollToDescriptionLabel));
    public static string TarotToggleFullscreenLabel => GetString(nameof(TarotToggleFullscreenLabel));
    public static string TarotDeckSelectionLabel => GetString(nameof(TarotDeckSelectionLabel));
    public static string TarotDeckSelectionPlaceholder => GetString(nameof(TarotDeckSelectionPlaceholder));
    public static string TarotDeckLoading => GetString(nameof(TarotDeckLoading));
    public static string NavigationBrand => GetString(nameof(NavigationBrand));
    public static string NavigationToggleTitle => GetString(nameof(NavigationToggleTitle));
    public static string NavigationHome => GetString(nameof(NavigationHome));
    public static string NavigationTarotCards => GetString(nameof(NavigationTarotCards));
    public static string NavigationDatabase => GetString(nameof(NavigationDatabase));
    public static string NavigationDataInfo => GetString(nameof(NavigationDataInfo));
    public static string NavigationImportExport => GetString(nameof(NavigationImportExport));
    public static string NavigationSettings => GetString(nameof(NavigationSettings));

    public static string NavigationSettingsCommon => GetString(nameof(NavigationSettingsCommon));

    public static string NavigationSettingsDecks => GetString(nameof(NavigationSettingsDecks));
    public static string NavigationInstructions => GetString(nameof(NavigationInstructions));
    public static string DatabasePageTitle => GetString(nameof(DatabasePageTitle));
    public static string DatabasePageHeader => GetString(nameof(DatabasePageHeader));
    public static string DataInfoPageTitle => GetString(nameof(DataInfoPageTitle));
    public static string DataInfoPageHeader => GetString(nameof(DataInfoPageHeader));
    public static string DataInfoDeckSelectionHeading => GetString(nameof(DataInfoDeckSelectionHeading));
    public static string DataInfoDeckSelectionLabel => GetString(nameof(DataInfoDeckSelectionLabel));
    public static string DataInfoShowReportButton => GetString(nameof(DataInfoShowReportButton));
    public static string DataInfoDeleteDeckButton => GetString(nameof(DataInfoDeleteDeckButton));
    public static string DataInfoDeckLoading => GetString(nameof(DataInfoDeckLoading));
    public static string DataInfoNoDecksMessage => GetString(nameof(DataInfoNoDecksMessage));
    public static string DataInfoReportLoading => GetString(nameof(DataInfoReportLoading));
    public static string DataInfoReportTitleFormat => GetString(nameof(DataInfoReportTitleFormat));
    public static string DataInfoReportCloseButtonLabel => GetString(nameof(DataInfoReportCloseButtonLabel));
    public static string DataInfoDeleteDeckLogTitle => GetString(nameof(DataInfoDeleteDeckLogTitle));
    public static string DataInfoDeleteDeckLogStartingFormat => GetString(nameof(DataInfoDeleteDeckLogStartingFormat));
    public static string DataInfoDeleteDeckLogCardCountFormat => GetString(nameof(DataInfoDeleteDeckLogCardCountFormat));
    public static string DataInfoDeleteDeckLogDeletingDeck => GetString(nameof(DataInfoDeleteDeckLogDeletingDeck));
    public static string DataInfoDeleteDeckLogDeckDeleted => GetString(nameof(DataInfoDeleteDeckLogDeckDeleted));
    public static string DataInfoDeleteDeckLogReloadingDecks => GetString(nameof(DataInfoDeleteDeckLogReloadingDecks));
    public static string DataInfoDeleteDeckLogFinished => GetString(nameof(DataInfoDeleteDeckLogFinished));
    public static string DataInfoDeleteDeckLogErrorFormat => GetString(nameof(DataInfoDeleteDeckLogErrorFormat));
    public static string ImportExportPageTitle => GetString(nameof(ImportExportPageTitle));
    public static string ImportExportPageHeader => GetString(nameof(ImportExportPageHeader));
    public static string ImportExportDeckImportHeading => GetString(nameof(ImportExportDeckImportHeading));
    public static string ImportExportDeckUploadLabel => GetString(nameof(ImportExportDeckUploadLabel));
    public static string ImportExportDeckUploadHint => GetString(nameof(ImportExportDeckUploadHint));
    public static string ImportExportDeckInvalidFileType => GetString(nameof(ImportExportDeckInvalidFileType));
    public static string ImportExportDeckFileTooLarge => GetString(nameof(ImportExportDeckFileTooLarge));
    public static string ImportExportDeckImportInProgress => GetString(nameof(ImportExportDeckImportInProgress));
    public static string ImportExportDeckImportSuccess => GetString(nameof(ImportExportDeckImportSuccess));
    public static string ImportExportDeckImportFailedFormat => GetString(nameof(ImportExportDeckImportFailedFormat));
    public static string ImportExportDeckMissingDeckName => GetString(nameof(ImportExportDeckMissingDeckName));
    public static string ImportExportDeckArchiveEmpty => GetString(nameof(ImportExportDeckArchiveEmpty));
    public static string ImportExportDeckNoCardsFound => GetString(nameof(ImportExportDeckNoCardsFound));
    public static string ImportExportDeckMissingImageFormat => GetString(nameof(ImportExportDeckMissingImageFormat));
    public static string ImportExportDeckMissingDescriptionFormat => GetString(nameof(ImportExportDeckMissingDescriptionFormat));
    public static string ImportExportDeckLogDescriptionFallbackFormat => GetString(nameof(ImportExportDeckLogDescriptionFallbackFormat));
    public static string ImportExportDeckReportTitleFormat => GetString(nameof(ImportExportDeckReportTitleFormat));
    public static string ImportExportDeckReportImageLengthLabel => GetString(nameof(ImportExportDeckReportImageLengthLabel));
    public static string ImportExportDeckReportDescriptionLengthLabel => GetString(nameof(ImportExportDeckReportDescriptionLengthLabel));
    public static string ImportExportDeckReportCloseButtonLabel => GetString(nameof(ImportExportDeckReportCloseButtonLabel));
    public static string ImportExportDeckLogTitle => GetString(nameof(ImportExportDeckLogTitle));
    public static string ImportExportDeckLogCloseButtonLabel => GetString(nameof(ImportExportDeckLogCloseButtonLabel));
    public static string ImportExportDeckLogStartingFormat => GetString(nameof(ImportExportDeckLogStartingFormat));
    public static string ImportExportDeckLogFileImportedFormat => GetString(nameof(ImportExportDeckLogFileImportedFormat));
    public static string ImportExportDeckLogExistingDeckFound => GetString(nameof(ImportExportDeckLogExistingDeckFound));
    public static string ImportExportDeckLogDeckDeleted => GetString(nameof(ImportExportDeckLogDeckDeleted));
    public static string ImportExportDeckLogDeckCreated => GetString(nameof(ImportExportDeckLogDeckCreated));
    public static string ImportExportDeckLogFinished => GetString(nameof(ImportExportDeckLogFinished));
    public static string InstructionsPageTitle => GetString(nameof(InstructionsPageTitle));
    public static string InstructionsPageHeader => GetString(nameof(InstructionsPageHeader));
    public static string InstructionsTableOfContentsLabel => GetString(nameof(InstructionsTableOfContentsLabel));
    public static string InstructionsContentError => GetString(nameof(InstructionsContentError));
    public static string SettingsPageTitle => GetString(nameof(SettingsPageTitle));
    public static string SettingsPageHeader => GetString(nameof(SettingsPageHeader));

    public static string SettingsDecksPageTitle => GetString(nameof(SettingsDecksPageTitle));

    public static string SettingsDecksPageHeader => GetString(nameof(SettingsDecksPageHeader));
    public static string SettingsThemeLabel => GetString(nameof(SettingsThemeLabel));
    public static string SettingsThemeDescription => GetString(nameof(SettingsThemeDescription));
    public static string SettingsThemeOptionLight => GetString(nameof(SettingsThemeOptionLight));
    public static string SettingsThemeOptionDark => GetString(nameof(SettingsThemeOptionDark));
    public static string SettingsSplashDurationLabel => GetString(nameof(SettingsSplashDurationLabel));
    public static string SettingsSplashDurationDescription => GetString(nameof(SettingsSplashDurationDescription));
    public static string SettingsCardScaleLabel => GetString(nameof(SettingsCardScaleLabel));
    public static string SettingsCardScaleDescription => GetString(nameof(SettingsCardScaleDescription));
    public static string SettingsSearchAutoClearLabel => GetString(nameof(SettingsSearchAutoClearLabel));
    public static string SettingsSearchAutoClearDescription => GetString(nameof(SettingsSearchAutoClearDescription));
    public static string SettingsCheckForUpdatesLabel => GetString(nameof(SettingsCheckForUpdatesLabel));
    public static string SettingsCheckForUpdatesDescription => GetString(nameof(SettingsCheckForUpdatesDescription));
    public static string HelpButtonLabelFormat => GetString(nameof(HelpButtonLabelFormat));
    public static string HelpCloseButtonLabel => GetString(nameof(HelpCloseButtonLabel));
    public static string HelpNotFoundMessage => GetString(nameof(HelpNotFoundMessage));
    public static string NotFoundPageTitle => GetString(nameof(NotFoundPageTitle));
    public static string NotFoundMessage => GetString(nameof(NotFoundMessage));
}
