// <auto-generated />
using System.Globalization;
using System.Resources;

namespace Toolbox.Resources;

/// <summary>
/// Stellt zentral verwaltete Anzeigetexte bereit.
/// </summary>
public static class DisplayTexts
{
    private static readonly ResourceManager ResourceManager = new("Toolbox.Resources.DisplayTexts", typeof(DisplayTexts).Assembly);

    private static string GetString(string resourceKey) => ResourceManager.GetString(resourceKey, CultureInfo.CurrentUICulture) ?? string.Empty;

    public static string HomePageTitle => GetString(nameof(HomePageTitle));
    public static string HomeWelcomeTitle => GetString(nameof(HomeWelcomeTitle));
    public static string HomeWelcomeDescription => GetString(nameof(HomeWelcomeDescription));
    public static string HomeTarotOverviewButton => GetString(nameof(HomeTarotOverviewButton));
    public static string TarotPageTitle => GetString(nameof(TarotPageTitle));
    public static string TarotHeader => GetString(nameof(TarotHeader));
    public static string TarotSearchInstructions => GetString(nameof(TarotSearchInstructions));
    public static string TarotSearchLabel => GetString(nameof(TarotSearchLabel));
    public static string TarotSearchPlaceholder => GetString(nameof(TarotSearchPlaceholder));
    public static string TarotSearchNotFound => GetString(nameof(TarotSearchNotFound));
    public static string TarotPreviousCardButton => GetString(nameof(TarotPreviousCardButton));
    public static string TarotNextCardButton => GetString(nameof(TarotNextCardButton));
    public static string TarotDeckSelectionLabel => GetString(nameof(TarotDeckSelectionLabel));
    public static string NavigationBrand => GetString(nameof(NavigationBrand));
    public static string NavigationToggleTitle => GetString(nameof(NavigationToggleTitle));
    public static string NavigationHome => GetString(nameof(NavigationHome));
    public static string NavigationTarotCards => GetString(nameof(NavigationTarotCards));
    public static string NotFoundPageTitle => GetString(nameof(NotFoundPageTitle));
    public static string NotFoundMessage => GetString(nameof(NotFoundMessage));
}
